server:
  port: 9006

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

spring:
  application:
    name: learn-cloud-consumer
  rabbitmq:
    port: 5672
    host: 39.99.248.217
    username: admin
    password: admin-rabbitmq
    listener:
      simple:
#        concurrency: 5  #最小的消费者数量
        ## 手动ack确认
        acknowledge-mode: manual  #表示消息确认方式，其有三种配置方式，分别是none、manual和auto；默认auto
        max-concurrency: 10  #最大的消费者数量
        prefetch: 1 #指定一个请求能处理多少个消息，如果有事务的话，必须大于等于transaction数量.
        retry:
          enabled: true  #开启消费重试机制
          max-attempts: 3  #消息处理异常重试次数
          max-interval: 10000 #重试最大间隔时间
          initial-interval: 2000 #重试初始时间
          multiplier: 2 #间隔时间乘子  例如：2 4 8 16
logging:
  config: classpath:logback-spring.xml
feign:
  hystrix:
    enabled: true

