server:
  port: 9000

spring:
  application:
    name: learn-cloud-producer

  rabbitmq:
    host: 39.99.248.217
    username: admin
    password: admin-rabbitmq
    publisher-confirms: true #设置此属性配置可以确保消息成功发送到交换器
    publisher-returns: true  #可以确保消息在未被队列接收时返回
    template:
      mandatory: true  #指定消息在没有被队列接收时是否强行退回还是直接丢弃,true或者false会忽略掉spring.rabbitmq.publisher-returns属性的值
    port: 5672
    connection-timeout: 2000 #连接超时，单位毫秒，0表示无穷大，不超时
    virtual-host: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    hostname: 127.0.0.1   # 配置使用主机名注册服务
    prefer-ip-address: true #优先使用ip地址进行注册服务
    ip-address: 127.0.0.1

logging:
  level:
    com.netflix: warn